version: '3.7'

services:
  main:
    container_name: wialon-parser-nest
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      #- node_modules:/usr/src/app/node_modules
    ports:
      - ${TCP_PORT}:${TCP_PORT}
    command: npm run start:dev
    env_file:
      - .env
  redis:
    container_name: wialon-parser-redis
    image: redis:7
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    env_file:
      - .env
  mongo:
    container_name: wialon-parser-mongo
    image: mongo:5
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
    